/**
 * Marketplace catalog — source of truth for registry.json.
 * Hand-maintained themes are listed here but not regenerated by scaffold.
 */

import { HTML5UP_TEMPLATES, html5UpThemeDef } from "./html5up-defs.ts";

export type CatalogTier = "inspired" | "faithful" | "html5up" | "base";

export interface CatalogEntry {
  slug: string;
  name: string;
  tier: CatalogTier;
  description: string;
  inspiredBy?: string;
  tags: string[];
  version: string;
  /** When true, `deno task scaffold` may regenerate packages/theme-{slug}/ */
  scaffold?: boolean;
}

/** Slugs managed by scripts/scaffold-themes.ts (THEME_DEFS). Empty when all themes are hand-maintained. */
export const SCAFFOLD_SLUGS = new Set<string>([]);

function html5UpCatalogEntries(): CatalogEntry[] {
  return HTML5UP_TEMPLATES.map((t) => {
    const def = html5UpThemeDef(t);
    return {
      slug: t.slug,
      name: t.name,
      tier: "html5up",
      description: def.description,
      inspiredBy: def.upstream,
      tags: def.tags,
      version: "1.0.0",
    };
  });
}

export const CATALOG: CatalogEntry[] = [
  // Inspired — hand-maintained
  {
    slug: "sirocco",
    name: "Sirocco",
    tier: "inspired",
    description: "Fast, clean minimalist blog inspired by Hugo PaperMod — Dune-native, not a port.",
    inspiredBy: "hugo-PaperMod",
    tags: ["blog", "minimal", "inspired"],
    version: "1.0.0",
  },
  {
    slug: "caravan",
    name: "Caravan",
    tier: "inspired",
    description: "Sidebar documentation theme inspired by hugo-book — Dune-native, not a port.",
    inspiredBy: "hugo-book",
    tags: ["docs", "sidebar", "inspired"],
    version: "1.0.0",
  },
  {
    slug: "fennec",
    name: "Fennec",
    tier: "inspired",
    description: "Personal portfolio and blog theme inspired by Astrofy — Dune-native, not a port.",
    inspiredBy: "Astrofy",
    tags: ["portfolio", "personal", "inspired"],
    version: "1.0.0",
  },
  {
    slug: "nightfall",
    name: "Nightfall",
    tier: "inspired",
    description: "Dark-first documentation theme inspired by Astro Starlight — Dune-native, not a port.",
    inspiredBy: "Starlight",
    tags: ["docs", "dark", "inspired"],
    version: "1.0.0",
  },
  {
    slug: "oasis",
    name: "Oasis",
    tier: "inspired",
    description: "Landing and academic résumé theme inspired by Hugo Blox — Dune-native, not a port.",
    inspiredBy: "Hugo Blox",
    tags: ["landing", "academic", "inspired"],
    version: "1.0.0",
  },
  {
    slug: "ink",
    name: "Ink",
    tier: "inspired",
    description: "Long-form writing theme inspired by Ghost Attila — Dune-native, not a port.",
    inspiredBy: "Attila",
    tags: ["blog", "writing", "serif", "inspired"],
    version: "1.0.0",
  },
  {
    slug: "gale",
    name: "Gale",
    tier: "inspired",
    description: "Landing and blog theme inspired by AstroWind — Dune-native, not a port.",
    inspiredBy: "AstroWind",
    tags: ["landing", "business", "inspired"],
    version: "1.0.0",
  },
  {
    slug: "salon",
    name: "Salon",
    tier: "inspired",
    description: "Magazine-style blog inspired by Ghost Liebling — Dune-native, not a port.",
    inspiredBy: "Liebling",
    tags: ["blog", "magazine", "inspired"],
    version: "1.0.0",
  },
  {
    slug: "syntax",
    name: "Syntax",
    tier: "inspired",
    description: "Technical blog theme inspired by Jekyll Chirpy — Dune-native, not a port.",
    inspiredBy: "jekyll-theme-chirpy",
    tags: ["blog", "tech", "inspired"],
    version: "1.0.0",
  },
  {
    slug: "herald",
    name: "Herald",
    tier: "inspired",
    description: "Publication-style blog inspired by Ghost Casper — Dune-native, not a port.",
    inspiredBy: "Casper",
    tags: ["blog", "publication", "inspired"],
    version: "1.0.0",
  },
  {
    slug: "lucid",
    name: "Lucid",
    tier: "inspired",
    description: "Modern docs theme inspired by Hugo Hextra — Dune-native, not a port.",
    inspiredBy: "Hextra",
    tags: ["docs", "modern", "inspired"],
    version: "1.0.0",
  },
  {
    slug: "manual",
    name: "Manual",
    tier: "inspired",
    description: "Product documentation theme inspired by Just the Docs — Dune-native, not a port.",
    inspiredBy: "Just the Docs",
    tags: ["docs", "product", "inspired"],
    version: "1.0.0",
  },
  // Faithful ports
  {
    slug: "papermod",
    name: "PaperMod for Dune",
    tier: "faithful",
    description: "Faithful port of Hugo PaperMod for Dune.",
    inspiredBy: "hugo-PaperMod",
    tags: ["blog", "minimal", "faithful"],
    version: "1.0.0",
  },
  {
    slug: "book",
    name: "Hugo Book for Dune",
    tier: "faithful",
    description: "Faithful port of hugo-book for Dune.",
    inspiredBy: "hugo-book",
    tags: ["docs", "sidebar", "faithful"],
    version: "1.0.0",
  },
  {
    slug: "starlight",
    name: "Starlight for Dune",
    tier: "faithful",
    description: "Faithful port of Astro Starlight for Dune.",
    inspiredBy: "Starlight",
    tags: ["docs", "modern", "faithful"],
    version: "1.0.0",
  },
  {
    slug: "blox",
    name: "Hugo Blox for Dune",
    tier: "faithful",
    description: "Faithful port of Hugo Blox for Dune.",
    inspiredBy: "Hugo Blox",
    tags: ["landing", "academic", "faithful"],
    version: "1.0.0",
  },
  // HTML5 UP (CC BY 3.0) — all 44 free templates
  ...html5UpCatalogEntries(),
  // Base
  {
    slug: "dune-minimal",
    name: "Dune Minimal",
    tier: "base",
    description: "Minimal semantic base theme — inherit via parent: dune-minimal",
    tags: ["base"],
    version: "1.0.0",
  },
];

/** Themes published to the marketplace registry (excludes base theme). */
export const MARKETPLACE_CATALOG = CATALOG.filter((e) => e.tier !== "base");

export function buildRegistryJson(catalog: CatalogEntry[] = MARKETPLACE_CATALOG) {
  return {
    version: 2,
    updatedAt: new Date().toISOString().slice(0, 10),
    themes: catalog.map((e) => ({
      slug: e.slug,
      name: e.name,
      description: e.description,
      author: "Dune Themes",
      version: e.version,
      license: "MIT",
      tags: e.tags,
      tier: e.tier,
      ...(e.inspiredBy ? { inspiredBy: e.inspiredBy } : {}),
      demoUrl: `https://themes.getdune.org/${e.slug}`,
      screenshotUrl: `https://themes.getdune.org/${e.slug}/themes/${e.slug}/static/screenshot.png`,
      jsr: `jsr:@dune/theme-${e.slug}@${e.version}`,
      downloadUrl:
        `https://github.com/duneorg/dune-themes/releases/download/${e.slug}-v${e.version}/${e.slug}-${e.version}.zip`,
      sha256: "",
      verified: true,
      downloads: 0,
      compatibleWith: "^0.28.0",
    })),
  };
}

export function packageDir(slug: string): string {
  return `packages/theme-${slug}`;
}
